In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from scipy.sparse import save_npz
# from sklearn.metrics.pairwise import cosine_similarity

In [2]:
from scipy.sparse import coo_matrix

In [3]:
datasetA=pd.read_csv(r"D:\PRJ1\PROJECT1\data\processed\Acleaned.csv")
datasetR=pd.read_csv(r"D:\PRJ1\PROJECT1\data\processed\Rcleaned.csv")

In [117]:
newR=pd.read_csv(r"D:\PRJ1\datasets\cleaneddatasets\reduced datasets\newR.csv")

In [4]:
dataset_AR=datasetR.merge(datasetA[["anime_id","name"]],on="anime_id")
dataset_AR

,user_id,anime_id,rating,name
0,3,20,8,Naruto
1,3,154,6,Shaman King
2,3,170,9,Slam Dunk
3,3,199,10,Sen to Chihiro no Kamikakushi
4,3,225,9,Dragon Ball GT
...,...,...,...,...
5695961,73515,13659,8,Ore no Imouto ga Konnani Kawaii Wake ga Nai.
5695962,73515,14345,7,Btooom!
5695963,73515,16512,7,Devil Survivor 2 The Animation
5695964,73515,17187,9,Ghost in the Shell: Arise - Border:1 Ghost Pain
5695965,73515,22145,10,Kuroshitsuji: Book of Circus

In [ ]:
# dataset=datasetA.merge(datasetR[["anime_id","user_id"]],on="anime_id")
# dataset

,anime_id,name,genre,type,episodes,rating,members,user_id
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,322
...,...,...,...,...,...,...,...,...
5695961,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211,58483
5695962,5543,Under World,Hentai,OVA,1,4.28,183,49503
5695963,5543,Under World,Hentai,OVA,1,4.28,183,58483
5695964,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219,49503
5695965,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,60365

**HERE I SWAPPED THE INDEX AND COLUMNS BECAUSE THE(1) NEEDS TO BE TRANSPOSED DUE TO SO MANY NAN**

**"IT IS SUGGESTED THAT TO USE KNN LOGIC INSTEAD OF COSINE SIM MATRIX IN THE GPT CHAT(then as mentioned the best approach is to use sparse matrix then what about cosine sim matrix problem) I'LL USE THE METHOD LATER"**

In [ ]:
# user_item_matrix=dataset_AR.pivot_table(index="name",columns="user_id",values="rating")
# # user_item_matrix(1)=dataset_AR.pivot_table(index="user_id",columns="name",values="rating")
# user_item_matrix=user_item_matrix.fillna(0)

MemoryError: Unable to allocate 2.43 GiB for an array with shape (9875, 32967) and data type float64

In [ ]:
# dataset_AR["rating"]=dataset_AR["rating"].astype("Float32")
# user_item_matrix=dataset_AR.pivot_table(index="name",columns="user_id",values="rating")
# sparse_matrix=csc_matrix(user_item_matrix.fillna(0).values)

# #DELETION OF USER_ITEM_MATRIX
# del user_item_matrix

In [ ]:
# similarity_matrix2=cosine_similarity(user_item_matrix)
# similarity_matrix2

NameError: name 'user_item_matrix' is not defined

**IT GOT CRASHED BECAUSE OF HUGE MEMORY(CAUSED OOM) SO DECIDED TO USE KNN APPROACH**

**-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

In [ ]:
# user_item_matrix=dataset_AR.pivot_table(index="name",columns="user_id",values="rating",fill_value=0).astype(np.float32)
# sparse_matrix=csc_matrix(user_item_matrix.values)

MemoryError: Unable to allocate 2.43 GiB for an array with shape (9875, 32967) and data type float64

**NEED TO REDUCE MY DATASET**

In [5]:
datasetA.shape

(9875, 7)

In [6]:
datasetR.head()

   user_id  anime_id  rating
0        3        20       8
1        3       154       6
2        3       170       9
3        3       199      10
4        3       225       9

In [7]:
active_users = datasetR["user_id"].value_counts()

active_users = active_users[
    active_users > 200
].index

datasetR = datasetR[
    datasetR["user_id"].isin(active_users)
]

In [12]:
total_values=datasetR["user_id"].value_counts()
total_values
useful_values=total_values[total_values>=200].index
useful_values

Index([42635, 53698, 57620, 59643, 51693, 45659,  7345, 12431, 65840, 22434,
       ...
       63478, 63865, 65884, 66155, 66316, 66406, 67326, 67831, 68441, 70562],
      dtype='int64', name='user_id', length=8638)

In [9]:
datasetR["user_id"].nunique()

8638

In [13]:
datasetR=datasetR[datasetR["user_id"].isin(useful_values)]
datasetR["user_id"].value_counts()

user_id
42635    3747
53698    2905
57620    2689
59643    2632
51693    2620
         ...
66406     201
67326     201
67831     201
68441     201
70562     201
Name: count, Length: 8638, dtype: int64

In [103]:
datasetR.to_csv(r"D:\PRJ1\datasets\cleaneddatasets\newR.csv",index=False)

In [ ]:
datasetA=datasetA[datasetA["anime_id"].isin(newR["anime_id"])]
datasetA.shape

(9786, 7)

In [118]:
newR['anime_id'].value_counts().count()

np.int64(9786)

In [119]:
newR["user_id"].value_counts().count()

np.int64(8713)

In [120]:
newR.shape

(3179694, 3)

In [112]:
datasetA.to_csv(r"D:\PRJ1\datasets\cleaneddatasets\newA.csv",index=False)

**KNN APPROACH:**

In [14]:
dataset_AR.shape

(5695966, 4)

In [32]:
ucate=dataset_AR["user_id"].astype("category")
acate=dataset_AR["name"].astype("category")

In [33]:
ucodes=ucate.cat.codes
acodes=acate.cat.codes

In [34]:
rating_values=dataset_AR["rating"].astype(np.float32)

In [35]:
sparse_matrix=coo_matrix((rating_values,(acodes,ucodes))).tocsr()

In [36]:
anime_names=acate.cat.categories

In [37]:
knn_model=NearestNeighbors(metric="cosine",algorithm="brute",n_neighbors=11)
knn_model.fit(sparse_matrix)
ani_to_index={anime:idx
              for idx, anime in enumerate(anime_names)}
index_to_ani={idx:anime
              for idx,anime in enumerate(anime_names)}

In [52]:
index_to_ani[7000]
# index_to_ani[1]
# index_to_ani[2]
# index_to_ani[3]
# index_to_ani[4]

'Princess Tutu'

In [43]:
print(anime_names[:10])

Index(['&quot;0&quot;', '&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi',
       '&quot;Bungaku Shoujo&quot; Memoire',
       '&quot;Bungaku Shoujo&quot; Movie', '&quot;Eiji&quot;',
       '.hack//G.U. Returner', '.hack//G.U. Trilogy',
       '.hack//G.U. Trilogy: Parody Mode', '.hack//Gift', '.hack//Intermezzo'],
      dtype='str')

In [44]:
type(anime_names[0])

str

In [62]:
def knn_recc_model(ani_name,no_recc=50):
    if ani_name not in ani_to_index:
        return "Anime not found!"
    ani_indx=ani_to_index[ani_name]
    distance,index=knn_model.kneighbors(sparse_matrix[ani_indx],n_neighbors=no_recc+1)
    recco=[]
    for i in range(1,len(distance.flatten())):
        recc_anime=index_to_ani[index.flatten()[i]]
        dist=distance.flatten()[i]
        recco.append(
            {"Anime":recc_anime,"Distance":dist}
        )
    return pd.DataFrame(recco)

In [66]:
knn_recc_model("Death Note")

                                                Anime  Distance
0                     Code Geass: Hangyaku no Lelouch  0.287312
1                  Code Geass: Hangyaku no Lelouch R2  0.313506
2                                          Elfen Lied  0.327108
3                                  Shingeki no Kyojin  0.335144
4                    Fullmetal Alchemist: Brotherhood  0.341472
5                                 Fullmetal Alchemist  0.362752
6                                    Sword Art Online  0.364545
7                                              Naruto  0.364884
8                                        Angel Beats!  0.374120
9                                    Mirai Nikki (TV)  0.390945
10                             Highschool of the Dead  0.391086
11                                        Steins;Gate  0.398835
12                                          Toradora!  0.404617
13                                     Ao no Exorcist  0.415078
14                                            Another  0.418264
15                                         Durarara!!  0.419405
16                                            Clannad  0.421377
17                                         Soul Eater  0.421982
18                      Sen to Chihiro no Kamikakushi  0.430202
19                         Tengen Toppa Gurren Lagann  0.432791
20                                 Deadman Wonderland  0.437593
21              Darker than Black: Kuro no Keiyakusha  0.444963
22                                        Tokyo Ghoul  0.458273
23                         Suzumiya Haruhi no Yuuutsu  0.458610
24                               Clannad: After Story  0.459259
25                                    No Game No Life  0.467326
26                            Neon Genesis Evangelion  0.472833
27                                        Psycho-Pass  0.476280
28                                      Dragon Ball Z  0.477432
29  Ano Hi Mita Hana no Namae wo Bokutachi wa Mada...  0.482221
30                                          Fate/Zero  0.483765
31                                     Bakemonogatari  0.485032
32                                    Fate/stay night  0.487830
33                                           Hellsing  0.491104
34                                       Kuroshitsuji  0.495179
35                             Ouran Koukou Host Club  0.502184
36                                           Claymore  0.502828
37                                   Samurai Champloo  0.504386
38                              Byousoku 5 Centimeter  0.504947
39                                       Guilty Crown  0.505494
40                                       Cowboy Bebop  0.506788
41                                Howl no Ugoku Shiro  0.506789
42                          Higurashi no Naku Koro ni  0.506924
43                                             Bleach  0.508560
44                                           Noragami  0.509316
45                                      One Punch Man  0.510952
46                         Mahou Shoujo Madoka★Magica  0.510969
47                                       Black Lagoon  0.514259
48                               Fate/Zero 2nd Season  0.515861
49                                            Btooom!  0.517103

**LOADING EVERYTHING IN MODELS FOLDER**

In [57]:
import joblib

In [58]:
joblib.dump(knn_model,"D:\PRJ1\PROJECT1\models/knn_model.pkl")

['D:\\PRJ1\\PROJECT1\\models/knn_model.pkl']

In [59]:
save_npz("D:\PRJ1\PROJECT1\models\sparse_matrix.npz",sparse_matrix)

In [60]:
joblib.dump(ani_to_index,r"D:\PRJ1\PROJECT1\models\ani_to_index.pkl")
joblib.dump(index_to_ani,r"D:\PRJ1\PROJECT1\models\index_to_ani.pkl")

['D:\\PRJ1\\PROJECT1\\models\\index_to_ani.pkl']