In [9]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
datasetA=pd.read_csv(r"D:\PRJ1\datasets\cleaneddatasets\Acleaned.csv")

In [11]:
datasetA.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

FOR OUR FISRT VERSION LETS BUILD ONLY USING ANIME DATASET AND ONLY REQUIRED ATTRIBUTES FROM THE DATASET(ANIMEID,NAME,GENRE,TYPE)

In [12]:
datasetA=datasetA[["anime_id","name","genre","type"]]
datasetA.head()

,anime_id,name,genre,type
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV

In [13]:
datasetA['genre_type_combined']=(datasetA['genre']+ " " +datasetA['type'])

In [14]:
datasetA.head()

,anime_id,name,genre,type,genre_type_combined
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,"Drama, Romance, School, Supernatural Movie"
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,"Action, Adventure, Drama, Fantasy, Magic, Mili..."
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,"Action, Comedy, Historical, Parody, Samurai, S..."
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,"Sci-Fi, Thriller TV"
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,"Action, Comedy, Historical, Parody, Samurai, S..."

In [15]:
datasetA['genre_type_combined']=datasetA['genre_type_combined'].str.lower()
datasetA['name']=datasetA['name'].str.lower()

TF_IDF

In [16]:
tf_idf=TfidfVectorizer(stop_words="english")
tf_idf_matrix=tf_idf.fit_transform(datasetA['genre_type_combined'])

In [17]:
similarity_matrix=cosine_similarity(tf_idf_matrix)
similarity_matrix

array([[1.        , 0.13624096, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.13624096, 1.        , 0.21757873, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.21757873, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ]], shape=(9875, 9875))

In [18]:
ind=pd.Series(datasetA.index,index=datasetA['name']).drop_duplicates()

In [19]:
ind['kimi no na wa.']

np.int64(0)

In [20]:
datasetA['name'][0]

'kimi no na wa.'

In [21]:
datasetA[datasetA['name']=="one punch man"]

,anime_id,name,genre,type,genre_type_combined
23,30276,one punch man,"Action, Comedy, Parody, Sci-Fi, Seinen, Super ...",TV,"action, comedy, parody, sci-fi, seinen, super ..."

**FIRST ML LOGIC (CONTENT BASED):**

In [22]:
def recomm_ani(ani_title,no_recomm=10):
    indices=ind[ani_title]
    sim_score=list(enumerate(similarity_matrix[indices]))
    sim_score=sorted(sim_score,key=lambda x: x[1],reverse=True)
    sim_score=sim_score[1:no_recomm+1]
    ani_inds=[i[0] for i in sim_score]
    return datasetA.iloc[ani_inds][["name","genre","type"]]

In [23]:
recomm_ani("hunter x hunter")

,name,genre,type
108,hunter x hunter,"Action, Adventure, Shounen, Super Power",TV
6975,big order (tv),"Action, Shounen, Super Power",TV
140,hunter x hunter ova,"Action, Adventure, Shounen, Super Power",OVA
141,hunter x hunter: greed island final,"Action, Adventure, Shounen, Super Power",OVA
196,hunter x hunter: greed island,"Action, Adventure, Shounen, Super Power",OVA
2008,hunter x hunter pilot,"Action, Adventure, Shounen, Super Power",OVA
4473,beast wars neo,"Action, Adventure, Mecha, Shounen, Super Power",TV
169,katekyo hitman reborn!,"Action, Comedy, Shounen, Super Power",TV
1938,hunter x hunter movie: phantom rouge,"Action, Adventure, Shounen, Super Power",Movie
2068,hunter x hunter movie: the last mission,"Action, Adventure, Shounen, Super Power",Movie

In [24]:
datasetA[datasetA['name']=="mousou dairinin"]

,anime_id,name,genre,type,genre_type_combined
961,323,mousou dairinin,"Drama, Mystery, Police, Psychological, Superna...",TV,"drama, mystery, police, psychological, superna..."