In [2]:
import pandas as pd
import numpy as np

In [77]:
data=pd.read_csv(r"D:\PRJ1\datasets\archive\anime.csv")
data.groupby("type").count()

         anime_id  name  genre  episodes  rating  members
type
Movie        2348  2348   2306      2348    2297     2348
Music         488   488    488       488     488      488
ONA           659   659    655       659     652      659
OVA          3311  3311   3310      3311    3285     3311
Special      1676  1676   1674      1676    1671     1676
TV           3787  3787   3777      3787    3671     3787

In [115]:
datasetR=pd.read_csv(r"D:\PRJ1\datasets\archive\rating.csv")
datasetR.head(20)

    user_id  anime_id  rating
0         1        20      -1
1         1        24      -1
2         1        79      -1
3         1       226      -1
4         1       241      -1
5         1       355      -1
6         1       356      -1
7         1       442      -1
8         1       487      -1
9         1       846      -1
10        1       936      -1
11        1      1546      -1
12        1      1692      -1
13        1      1836      -1
14        1      2001      -1
15        1      2025      -1
16        1      2144      -1
17        1      2787      -1
18        1      2993      -1
19        1      3455      -1

In [297]:
datasetA=pd.read_csv(r"D:\PRJ1\datasets\archive\anime.csv")
datasetA.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [259]:
datasetA.describe()

           anime_id       rating       members
count   9875.000000  9875.000000  9.875000e+03
mean   11402.152405     6.593161  2.193690e+04
std    10457.018598     0.961845  5.991996e+04
min        1.000000     2.000000  3.300000e+01
25%     2694.500000     6.060000  6.025000e+02
50%     7475.000000     6.670000  2.561000e+03
75%    18833.000000     7.260000  1.395950e+04
max    34475.000000     9.370000  1.013917e+06

In [258]:
datasetA.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [301]:
datasetA=datasetA.dropna(subset=["genre","type"])

In [302]:
datasetA.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [36]:
datasetA.shape

(12210, 7)

In [298]:
datasetA["rating"]=datasetA["rating"].fillna(datasetA["rating"].median())

In [46]:
print(datasetA.to_string())

       anime_id                                                                                                  name                                                                                                                          genre     type episodes  rating  members
0         32281                                                                                        Kimi no Na wa.                                                                                           Drama, Romance, School, Supernatural    Movie        1    9.37   200630
1          5114                                                                      Fullmetal Alchemist: Brotherhood                                                                    Action, Adventure, Drama, Fantasy, Magic, Military, Shounen       TV       64    9.26   793665
2         28977                                                                                              Gintama°                                                                   Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen       TV       51    9.25   114262
3          9253                                                                                           Steins;Gate                                                                                                               Sci-Fi, Thriller       TV       24    9.17   673572
4          9969                                                                                         Gintama&#039;                                                                   Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen       TV       51    9.16   151266
5         32935                                             Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou                                                                                         Comedy, Drama, School, Shounen, Sports       TV       10    9.15    93351
6         11061                                                                                Hunter x Hunter (2011)                                                                                        Action, Adventure, Shounen, Super Power       TV      148    9.13   425855
7           820                                                                                  Ginga Eiyuu Densetsu                                                                                                 Drama, Military, Sci-Fi, Space      OVA      110    9.11    80679
8         15335                                                   Gintama Movie: Kanketsu-hen - Yorozuya yo Eien Nare                                                                   Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen    Movie        1    9.10    72534
9         15417                                                                              Gintama&#039;: Enchousen                                                                   Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen       TV       13    9.11    81109
10         4181                                                                                  Clannad: After Story                                                                           Drama, Fantasy, Romance, Slice of Life, Supernatural       TV       24    9.06   456749
11        28851                                                                                        Koe no Katachi                                                                                                         Drama, School, Shounen    Movie        1    9.05   102733
12          918                                                                                               Gintama                                                                   Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen       TV      201    9.04   336376
13         2904                                                                    Code Geass: Hangyaku no Lelouch R2                                                                            Action, Drama, Mecha, Military, Sci-Fi, Super Power       TV       25    8.98   572888
14        28891                                                                               Haikyuu!! Second Season                                                                                         Comedy, Drama, School, Shounen, Sports       TV       25    8.93   179342
15          199                                                                         Sen to Chihiro no Kamikakushi                                                                                                 Adventure, Drama, Supernatural    Movie        1    8.93   466254
16        23273                                                                               Shigatsu wa Kimi no Uso                                                                                         Drama, Music, Romance, School, Shounen       TV       22    8.92   416397
17        24701                                                                         Mushishi Zoku Shou 2nd Season                                                   Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural       TV       10    8.88    75894
18        12355                                                                          Ookami Kodomo no Ame to Yuki                                                                                                         Fantasy, Slice of Life    Movie        1    8.84   226193
19         1575                                                                       Code Geass: Hangyaku no Lelouch                                                                           Action, Mecha, Military, School, Sci-Fi, Super Power       TV       25    8.83   715151
20          263                                                                                        Hajime no Ippo                                                                                                 Comedy, Drama, Shounen, Sports       TV       75    8.83   157670
21           44                                                 Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen                                                                      Action, Drama, Historical, Martial Arts, Romance, Samurai      OVA        4    8.83   129307
22            1                                                                                          Cowboy Bebop                                                                                Action, Adventure, Comedy, Drama, Sci-Fi, Space       TV       26    8.82   486824
23        30276                                                                                         One Punch Man                                                              Action, Comedy, Parody, Sci-Fi, Seinen, Super Power, Supernatural       TV       12    8.82   552458
24          164                                                                                         Mononoke Hime                                                                                                     Action, Adventure, Fantasy    Movie        1    8.81   339556
25         7311                                                                         Suzumiya Haruhi no Shoushitsu                                                                         Comedy, Mystery, Romance, School, Sci-Fi, Supernatural    Movie        1    8.81   240297
26        17074                                                                      Monogatari Series: Second Season                                                                                Comedy, Mystery, Romance, Supernatural, Vampire       TV       26    8.80   205959
27        21939                                                                                    Mushishi Zoku Shou                                                   Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural       TV       10    8.80   101351
28          457                                                                                              Mushishi                                                   Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural       TV       26    8.78   300030
29         2001                                                                            Tengen Toppa Gurren Lagann                                                                                       Action, Adventure, Comedy, Mecha, Sci-Fi       TV       27    8.78   562962
30          245                                                                                 Great Teacher Onizuka                                                                                  Comedy, Drama, School, Shounen, Slice of Life       TV       43    8.77   268487
31        32983                                                                                 Natsume Yuujinchou Go                                                                            Drama, Fantasy, Shoujo, Slice of Life, Supernatural       TV       13    8.76    38865
32         5258                                                                        Hajime no Ippo: New Challenger                                                                                                 Comedy, Drama, Shounen, Sports       TV       26    8.75    88995
33        28957                                                                   Mushishi Zoku Shou: Suzu no Shizuku                                                   Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural    Movie        1    8.75    32266
34        11665                                                                                Natsume Yuujinchou Shi                                                                            Drama, Fantasy, Shoujo, Slice of Life, Supernatural       TV       13    8.75    98431
35          431                                                                                   Howl no Ugoku Shiro                                                                                             Adventure, Drama, Fantasy, Romance    Movie        1    8.74   333186
36        11741                                                                                  Fate/Zero 2nd Season                                                                                        Action, Fantasy, Supernatural, Thriller       TV       12    8.73   340973
37        31757                                                                       Kizumonogatari II: Nekketsu-hen                                                                                         Action, Mystery, Supernatural, Vampire    Movie        1    8.73    34347
38           19                                                                                               Monster                                                                Drama, Horror, Mystery, Police, Psychological, Seinen, Thriller       TV       74    8.72   247562
39        12365                                                                                   Bakuman. 3rd Season                                                                                                Comedy, Drama, Romance, Shounen       TV       25    8.71   133620
40         1535                                                                                            Death Note                                                                         Mystery, Police, Psychological, Supernatural, Thriller       TV       37    8.71  1013917
41        32366                                                                            Gintama°: Aizome Kaori-hen                                                                                                                 Comedy, Parody      OVA        2    8.69    16947
42        30654                                                                    Ansatsu Kyoushitsu (TV) 2nd Season                                                                                                Action, Comedy, School, Shounen       TV       25    8.68   176475
43        20583                                                                                             Haikyuu!!                                                                                         Comedy, Drama, School, Shounen, Sports       TV       25    8.68   284498
44        19647                                                                                Hajime no Ippo: Rising                                                                                                 Comedy, Drama, Shounen, Sports       TV       25    8.68    66756
45         4282                                                                        Kara no Kyoukai 5: Mujun Rasen                                                                        Action, Drama, Mystery, Romance, Supernatural, Thriller    Movie        1    8.68   111074
46        10379                                                                                Natsume Yuujinchou San                                                                            Drama, Fantasy, Shoujo, Slice of Life, Supernatural       TV       13    8.67   102322
47        22135                                                                               Ping Pong The Animation                                                                                                  Psychological, Seinen, Sports       TV       11    8.67    97187
48        21329                                                                          Mushishi Special: Hihamukage                                                   Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural  Special        1    8.66    49036
49        31043                                                                               Boku dake ga Inai Machi                                                                                   Mystery, Psychological, Seinen, Supernatural       TV       12    8.65   402381
50         7785                                                                                Yojouhan Shinwa Taikei                                                                                                Mystery, Psychological, Romance       TV       11    8.65   122531
51         3297                                                                                  Aria The Origination                                                                                        Fantasy, Sci-Fi, Shounen, Slice of Life       TV       13    8.64    56162
52        30709                                                                      Kamisama Hajimemashita: Kako-hen                                                                                  Comedy, Demons, Fantasy, Shoujo, Supernatural      OVA        4    8.64    33422
53         6114                                                                   Rainbow: Nisha Rokubou no Shichinin                                                                                            Drama, Historical, Seinen, Thriller       TV       26    8.64   139474
54        31240                                                                 Re:Zero kara Hajimeru Isekai Seikatsu                                                                                        Drama, Fantasy, Psychological, Thriller       TV       25    8.64   355839
55         4565                                                          Tengen Toppa Gurren Lagann Movie: Lagann-hen                                                                                      Action, Mecha, Sci-Fi, Space, Super Power    Movie        1    8.64    82253
56         5300                                                                               Zoku Natsume Yuujinchou                                                                            Drama, Fantasy, Shoujo, Slice of Life, Supernatural       TV       13    8.64   114173
57         9989                                              Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.                                                                                             Drama, Slice of Life, Supernatural       TV       11    8.62   463835
58        24415                                                                           Kuroko no Basket 3rd Season                                                                                                Comedy, School, Shounen, Sports       TV       25    8.62   184525
59        11577                                                            Steins;Gate Movie: Fuka Ryouiki no Déjà vu                                                                                                               Sci-Fi, Thriller    Movie        1    8.61   192424
60        10408                                                                                    Hotarubi no Mori e                                                                                           Drama, Romance, Shoujo, Supernatural    Movie        1    8.61   197439
61        28171                                                                                    Shokugeki no Souma                                                                                                         Ecchi, School, Shounen       TV       24    8.61   348951
62        32995                                                                                        Yuri!!! on Ice                                                                                                                 Comedy, Sports       TV       12    8.61   103178
63        21899                                                           Gintama: Yorinuki Gintama-san on Theater 2D                                                                   Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen    Movie        2    8.60    11104
64        26055                                               JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season                                                                                Action, Adventure, Drama, Shounen, Supernatural       TV       24    8.60    93657
65         7472                                                                Gintama Movie: Shinyaku Benizakura-hen                                                                   Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen    Movie        1    8.59    51185
66          777                                                                                     Hellsing Ultimate                                                                        Action, Horror, Military, Seinen, Supernatural, Vampire      OVA       10    8.59   297454
67        22535                                                                            Kiseijuu: Sei no Kakuritsu                                                                           Action, Drama, Horror, Psychological, Sci-Fi, Seinen       TV       24    8.59   425457
68        28735                                                                         Shouwa Genroku Rakugo Shinjuu                                                                                                       Drama, Historical, Josei       TV       13    8.59    71295
69        12431                                                                                         Uchuu Kyoudai                                                                                   Comedy, Sci-Fi, Seinen, Slice of Life, Space       TV       99    8.59    72958

In [51]:
datasetR.isnull().sum()

user_id     0
anime_id    0
rating      0
dtype: int64

In [53]:
datasetR.shape,datasetA.shape

((7813737, 3), (12210, 7))

In [54]:
(32281 in datasetA["anime_id"].values) and (32281 in datasetR["anime_id"].values)

True

In [55]:
datasetA[datasetA["anime_id"]==32281]

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630

In [63]:
datasetR[datasetR["anime_id"]==32281]

         user_id  anime_id  rating
8271          99     32281       5
11961        152     32281      10
19665        244     32281      10
22985        271     32281      10
23382        278     32281      -1
...          ...       ...     ...
7758439    73042     32281       9
7763841    73099     32281      10
7764599    73109     32281       9
7791788    73311     32281       7
7792479    73319     32281       8

[2199 rows x 3 columns]

In [64]:
11771 in datasetA["anime_id"]

True

In [67]:
datasetA[datasetA["anime_id"]==11771]

,anime_id,name,genre,type,episodes,rating,members
122,11771,Kuroko no Basket,"Comedy, School, Shounen, Sports",TV,25,8.46,338315

In [76]:
datasetA.groupby(["type"]).count()

         anime_id  name  genre  episodes  rating  members
type
Movie        2306  2306   2306      2306    2306     2306
Music         488   488    488       488     488      488
ONA           655   655    655       655     655      655
OVA          3310  3310   3310      3310    3310     3310
Special      1674  1674   1674      1674    1674     1674
TV           3777  3777   3777      3777    3777     3777

In [12]:
datasetR.groupby(["user_id"]).count()

         anime_id  rating
user_id
1             153     153
2               3       3
3              94      94
4              52      52
5             467     467
...           ...     ...
73512          13      13
73513          33      33
73514           1       1
73515         196     196
73516           2       2

[73515 rows x 2 columns]

In [303]:
datasetA[datasetA.duplicated()]

Empty DataFrame
Columns: [anime_id, name, genre, type, episodes, rating, members]
Index: []

In [246]:
datasetR[datasetR.duplicated(keep=False)]

Empty DataFrame
Columns: [user_id, anime_id, rating]
Index: []

In [123]:
datasetR[datasetR.duplicated()]

Empty DataFrame
Columns: [user_id, anime_id, rating]
Index: []

In [66]:
datasetR.loc[4499258]

user_id     42653
anime_id    16498
rating          8
Name: 4499258, dtype: int64

In [124]:
datasetR=datasetR.drop_duplicates()

In [37]:
datasetR.loc[7813736]

user_id     73516
anime_id     8074
rating          9
Name: 7813736, dtype: int64

In [304]:
datasetA.shape

(12210, 7)

In [128]:
datasetR.shape

(6337240, 3)

In [306]:
(datasetR["rating"]==-1).sum()

np.int64(0)

In [61]:
print(7813736-1476496)

6337240

In [72]:
datasetR.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6337240 entries, 47 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 193.4 MB

In [252]:
datasetA.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9875 entries, 0 to 12292
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  9875 non-null   int64
 1   name      9875 non-null   object
 2   genre     9875 non-null   object
 3   type      9875 non-null   object
 4   episodes  9875 non-null   object
 5   rating    9874 non-null   float64
 6   members   9875 non-null   int64
dtypes: float64(1), int64(2), object(4)
memory usage: 617.2+ KB

In [127]:
datasetR=datasetR[datasetR["rating"]!=-1]

In [74]:
datasetA["rating"]

0        9.37
1        9.26
2        9.25
3        9.17
4        9.16
         ...
12289    4.15
12290    4.28
12291    4.88
12292    4.98
12293    5.46
Name: rating, Length: 12294, dtype: float64

In [315]:
s1=set(datasetA["anime_id"]) 
len(s1)

9875

In [314]:
s2=set(datasetR["anime_id"])
len(s2)

9875

In [313]:
s3=s1.intersection(s2)
len(s3)

9875

In [312]:
haha=set(datasetA["anime_id"])-set(datasetR["anime_id"])
len(haha)

0

In [130]:
len(s1)-len(s2)

0

In [311]:
datasetA=datasetA[datasetA['anime_id'].isin(datasetR['anime_id'])]
datasetA.shape

(9875, 7)

In [250]:
datasetR=datasetR[datasetR["anime_id"].isin(datasetA['anime_id'])]

In [143]:
datasetR['anime_id'].value_counts()

anime_id
1535     34226
11757    26310
16498    25289
1575     24126
6547     23565
         ...
23393        1
22221        1
26123        1
29837        1
8749         1
Name: count, Length: 9926, dtype: int64

In [148]:
datasetR[datasetR["anime_id"]==8749]

         user_id  anime_id  rating
7776587    73188      8749       6

In [138]:
datasetR.head(20)

     user_id  anime_id  rating
47         1      8074      10
81         1     11617      10
83         1     11757      10
101        1     15451      10
153        2     11771      10
156        3        20       8
157        3       154       6
158        3       170       9
159        3       199      10
160        3       225       9
161        3       341       6
162        3       430       7
163        3       527       7
164        3       552       7
165        3       813      10
166        3      1119       7
167        3      1121       7
168        3      1122       7
169        3      1132       8
170        3      1292       6

In [268]:
total_users=datasetR['user_id'].value_counts()
# useful_users=total_users[total_users>=50]
total_users

user_id
42635    3747
53698    2905
57620    2689
59643    2632
51693    2620
         ...
33607      50
31914      50
66821      50
67655      50
6386       50
Name: count, Length: 32967, dtype: int64

In [267]:
useful_users=total_users[total_users>=50].index
len(useful_users)

32967

In [266]:
datasetR=datasetR[datasetR['user_id'].isin(useful_users)]
len(datasetR)

5695966

In [183]:
datasetR.nunique()

user_id     32967
anime_id     9908
rating         10
dtype: int64

In [184]:
datasetA.nunique()

anime_id    9926
name        9926
genre       3048
type           6
episodes     178
rating       574
members     6474
dtype: int64

In [195]:
datasetR[datasetR['anime_id']==21]

Empty DataFrame
Columns: [user_id, anime_id, rating]
Index: []

In [264]:
datasetA.loc[73]

anime_id                              5028
name                              Major S5
genre       Comedy, Drama, Romance, Sports
type                                    TV
episodes                                25
rating                                8.58
members                              28653
Name: 73, dtype: object

In [271]:
datasetA["name"]=datasetA['name'].str.lower()
datasetA.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,kimi no na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,fullmetal alchemist: brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,steins;gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [276]:
datasetA.loc[73]

anime_id                              5028
name                              major s5
genre       Comedy, Drama, Romance, Sports
type                                    TV
episodes                                25
rating                                8.58
members                              28653
Name: 73, dtype: object

In [277]:
datasetA.loc[74]

KeyError: 74

In [317]:
datasetA=datasetA.reset_index(drop=True)
datasetR=datasetR.reset_index(drop=True)

In [319]:
datasetA.loc[74]

anime_id                                   17389
name                          Kingdom 2nd Season
genre       Action, Historical, Military, Seinen
type                                          TV
episodes                                      39
rating                                      8.57
members                                    31234
Name: 74, dtype: object

In [320]:
datasetA.to_csv(r"D:\PRJ1\datasets\cleaneddatasets\Acleaned.csv",index=False)
datasetR.to_csv(r"D:\PRJ1\datasets\cleaneddatasets\Rcleaned.csv",index=False)